---
resources:
- name: pipeline-changes
  type: git
  source:
    uri: {{pipeline-git-repo}}

- name: git-vault-concourse-docker-image
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: master

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-task-image}}

jobs:
- name: job-hello-world
  public: true
  plan:
  - aggregate:
    - get: pipeline-changes
      trigger: true

  - task: hello-world
    config:
      inputs:
      - {name: pipeline-changes, path: .}
      platform: linux
      image: {{docker-hub-gug-image}}
      run:
        path: ./bin/get-secret
        args:
        - {{vault-token}}
        - {{vault-address}}
        - 'secret/hello'

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-vault-concourse-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-vault-concourse-docker-image/ci_image
