---
resources:
- name: pipeline-changes
  type: git
  source:
    uri: {{pipeline-git-repo}}
    paths:
    - ./*.yml
    - bin/*

- name: git-docker-image
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: master
    paths: [ci_image/Dockerfile]

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-task-image}}

jobs:
- name: vault-query-example
  public: true
  plan:
  - aggregate:
    - get: pipeline-changes
      trigger: true
    - get: docker-image
      trigger: true

  - task: query-vault
    config:
      inputs:
      - {name: pipeline-changes, path: .}
      platform: linux
      image: {{docker-hub-gug-image}}
      run:
        path: ./bin/get-secret
        args:
        - {{vault-token}}
        - {{vault-address}}
        - 'secret/hello'
        - 'excited'

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-docker-image/ci_image
